#!/usr/bin/env python3
"""
Generate sdc/bench_top_v3.sdc from v2 by scaling, so no number is hand-typed.

WHY v3 EXISTS. v2 set each period ~10% tighter than the domain's measured
baseline requirement. That baseline came from a flow that was missing a
standard buffering pass (see experiments/buffering_control/), so v2's targets
were derived from a capability the design does not actually have: with
`buffer; upsize; dnsize` the same netlist meets every v2 target with 12 to 20
ns to spare. A target you clear by 20 ns is not a closure target.

v3 applies v2's OWN methodology to the corrected flow: ~10% tighter than the
measured POST-BUFFERING requirement.

    domain   post-buffer required   v3 target   demanded
    clk_a           17.216            15.5       1.716 ns  (10.0%)
    clk_b           13.900            12.5       1.400 ns  (10.1%)
    clk_e            6.106             5.5       0.606 ns  ( 9.9%)
    clk_c            met at 3.0        3.0       unchanged
    clk_d            met at 8.0        8.0       unchanged

I/O delays are scaled by the same per-domain factor, so they keep the same
fraction of the period they had in v2. Without that, shrinking clk_e's period
from 26.5 to 5.5 while leaving a 2.7 ns input delay would make I/O paths
binding instead of the logic, and the loop would be classifying the wrong
thing.

Generated-clock -edges are relative to master edges and scale automatically.

v1 and v2 are NOT deleted. Both remain the frozen record for the measurements
published against them.
"""
import io, os, re

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "bench_top_v2.sdc")
OUT = os.path.join(HERE, "bench_top_v3.sdc")

# post-buffering measured requirement = v2 period - v2 post-buffer slack
REQUIRED = {"clk_a": 30.0 - 12.784, "clk_b": 26.5 - 12.600,
            "clk_e": 26.5 - 20.394}
NEW_PERIOD = {"clk_a": 15.5, "clk_b": 12.5, "clk_e": 5.5,
              "clk_c": 3.0, "clk_d": 8.0}
OLD_PERIOD = {"clk_a": 30.0, "clk_b": 26.5, "clk_c": 3.0,
              "clk_d": 8.0, "clk_e": 26.5}
SCALE = {c: NEW_PERIOD[c] / OLD_PERIOD[c] for c in OLD_PERIOD}

# which clock each constrained port group is timed against
PORT_CLOCK = {
    "data_in_a valid_in_a": "clk_a",
    "cfg_addr_e cfg_wdata_e cfg_we_e": "clk_e",
    "mac_result_a": "clk_a",       # clk_a_div2, scales with clk_a
    "status_b": "clk_b",
    "uart_tx_c": "clk_c",
    "timer_pulse_d": "clk_d",
    "cfg_status_e": "clk_e",
}

src = io.open(SRC, encoding="utf-8").read()
out, n_period, n_io = src, 0, 0

for clk, p in NEW_PERIOD.items():
    pat = re.compile(rf"(create_clock -name {clk} -period )([0-9.]+)")
    out, k = pat.subn(lambda m: m.group(1) + str(p), out)
    n_period += k
    assert k == 1, f"{clk}: matched {k} create_clock lines"

# scale set_input_delay / set_output_delay by the domain factor
def scale_io(m):
    """Scale the delay value, leaving the get_ports expression byte-identical.
    An earlier version rebuilt the bracket form and appended a brace to
    single-port lines that never had one, producing `[get_ports mac_result_a}]`
    and an SDC OpenSTA rejects."""
    global n_io
    head, val, ports_expr = m.group(1), float(m.group(2)), m.group(3)
    names = re.findall(r"[\w]+", ports_expr.replace("get_ports", ""))
    key = next((k for k in PORT_CLOCK if set(k.split()) == set(names)), None)
    if key is None:
        return m.group(0)
    n_io += 1
    return f"{head}{round(val * SCALE[PORT_CLOCK[key]], 3)}{ports_expr}"

out = re.sub(
    r"(set_(?:in|out)put_delay -clock \w+ -(?:max|min) )([0-9.]+)"
    r"( \[get_ports [^\]]*\])",
    scale_io, out)

hdr = f"""###############################################################################
# bench_top_v3.sdc -- CLOSURE TARGETS for the flow that includes the
# buffering pass, generated by sdc/make_v3.py. Do not hand-edit.
#
# v2 derived its targets from a flow that was missing a standard buffering
# pass. With `buffer; upsize; dnsize` the same netlist clears every v2 target
# by 12 to 20 ns, and a target you clear by 20 ns is not a closure target.
# v3 applies v2's own methodology to the corrected flow: ~10% tighter than
# the measured POST-BUFFERING requirement.
#
#   domain   post-buffer required   v3 target   demanded
#   clk_a          {REQUIRED['clk_a']:.3f}             15.5      1.716 ns  (10.0%)
#   clk_b          {REQUIRED['clk_b']:.3f}             12.5      1.400 ns  (10.1%)
#   clk_e           {REQUIRED['clk_e']:.3f}              5.5      0.606 ns  ( 9.9%)
#   clk_c          met                   3.0      unchanged
#   clk_d          met                   8.0      unchanged
#
# I/O delays are scaled by the same per-domain factor so they keep the same
# fraction of the period they had in v2. Otherwise shrinking clk_e from 26.5
# to 5.5 while leaving a 2.7 ns input delay would make I/O paths binding
# instead of the logic.
#
# v1 and v2 are NOT deleted; both stay frozen as the record for the
# measurements published against them.
###############################################################################

"""
out = hdr + out[out.index("# ------"):]
io.open(OUT, "w", encoding="utf-8", newline="\n").write(out)
print(f"wrote {OUT}: {n_period} periods rescaled, {n_io} I/O delays scaled")
for c in sorted(NEW_PERIOD):
    print(f"  {c}: {OLD_PERIOD[c]} -> {NEW_PERIOD[c]}  (scale {SCALE[c]:.4f})")
