#!/usr/bin/env python3
"""
run_proof.py -- generate the standard three-task SBY config and run it.

Every .sby file in this project (experiments/fsm_reencode/miter.sby,
experiments/mux_priority_to_parallel/miter_scoped.sby,
experiments/pipeline_cut_domain_a/miter.sby) has an IDENTICAL [tasks],
[options] and [engines] block -- verified by diff before writing this tool,
not assumed. Only [script] and [files] differ, and those differ only in
which source files a given obligation needs. This automates exactly that
constant part, and runs the three tasks, parsing each into the same
PASS/FAIL/PROVEN-per-property summary this project has been hand-writing
into NOTES.md three times now.

This does NOT decide what obligation to prove or how to scope it -- writing
the miter itself (the actual proof content: what's assumed, what's
asserted, why) stays a judgment call. This only removes the busywork of
re-deriving the same six-line SBY boilerplate and re-reading the same log
patterns by eye each time.

Usage:
    python3 run_proof.py --top miter_mapped \\
        --file domain_b_fv.v --file domain_b_onehot_fv.v \\
        --file decode_state.vh --file miter_mapped.sv \\
        --workdir experiments/fsm_reencode --tasks bmc,prove,pdr

Files passed via --file are BOTH read (for -sv) and copied (via [files]) --
matching this project's established convention. A .vh include fragment
should still be listed via --file so SBY's sandbox has it available, but
is not itself given a `read_verilog` line (matching how decode_state.vh has
always been handled: pulled in by `include` inside a .v file, not read
standalone). Detected automatically by the .vh extension.

Requires `sby` on PATH (this project's OSS CAD Suite build).
"""

import argparse
import os
import re
import subprocess
import sys


SBY_TEMPLATE = """# Generated by tools/run_proof.py -- do not hand-edit the [tasks]/[options]/
# [engines] blocks below; they are the verified-identical boilerplate shared
# by every proof in this project (see the tool's own docstring for the diff
# that established this). Edit [script]/[files] by re-running the tool with
# different --file/--top arguments instead.
#
# `cover` checks that a cover() statement's condition is REACHABLE within
# depth -- added after mutation-testing a real stream-equivalence proof
# showed a design that deadlocks before completing any transaction passes
# its safety assert vacuously (the assert's own guard condition was never
# reached). A stream-equivalence proof without a matching cover check
# proves nothing has gone wrong only in the sense that nothing was ever
# checked -- run cover on any property gated behind a "both sides
# completed a transaction"-style precondition, which is every branch-3
# proof in this project.

[tasks]
bmc
prove
pdr
cover

[options]
bmc:   mode bmc
bmc:   depth {depth}
prove: mode prove
prove: depth {depth}
pdr:   mode prove
cover: mode cover
cover: depth {depth}

[engines]
bmc:   smtbmc z3
prove: smtbmc z3
pdr:   abc pdr
cover: smtbmc z3

[script]
{script_lines}
prep -top {top}

[files]
{files_lines}
"""


def build_sby(top: str, files: list, depth: int) -> str:
    script_lines = "\n".join(
        f"read_verilog -formal -sv {f}" for f in files if not f.endswith(".vh")
    )
    files_lines = "\n".join(files)
    return SBY_TEMPLATE.format(
        depth=depth, top=top, script_lines=script_lines, files_lines=files_lines
    )


def run_task(sby_bin: str, sby_path: str, task: str, workdir: str, timeout: int):
    run_dir = os.path.join(workdir, f"{os.path.splitext(os.path.basename(sby_path))[0]}_{task}")
    if os.path.isdir(run_dir):
        subprocess.run(["rm", "-rf", run_dir])
    try:
        proc = subprocess.run(
            [sby_bin, "-f", os.path.basename(sby_path), task],
            cwd=workdir,
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        return proc.returncode, proc.stdout + proc.stderr, False
    except subprocess.TimeoutExpired as e:
        out = (e.stdout or b"").decode("utf-8", "replace") if isinstance(e.stdout, bytes) else (e.stdout or "")
        err = (e.stderr or b"").decode("utf-8", "replace") if isinstance(e.stderr, bytes) else (e.stderr or "")
        return None, out + err, True


def parse_result(task: str, log: str, timed_out: bool):
    """Best-effort parse into (verdict, detail). Never guesses silently --
    falls back to UNPARSED with a pointer to the raw log rather than
    reporting a verdict it did not actually see."""
    if timed_out:
        return "TIMEOUT", "stopped by wrapper timeout, not a tool verdict -- inspect raw log"

    if task in ("bmc", "pdr"):
        # SBY's own top-level verdict line is the reliable one -- e.g.
        # "DONE (PASS, rc=0)" / "DONE (FAIL, rc=2)". The per-engine
        # "returned pass"/"returned FAIL" line is inconsistently cased
        # across SBY versions (confirmed directly: this project's real log
        # said "returned pass", lowercase, which an earlier version of this
        # parser missed by matching only uppercase PASS/FAIL -- fixed here
        # by anchoring on DONE instead, not by loosening the case match,
        # since a loosened regex risks matching the wrong line entirely).
        m = re.search(r"DONE \((PASS|FAIL)", log)
        if m:
            time_m = re.search(r"Elapsed clock time.*\((\d+)\)", log)
            secs = time_m.group(1) if time_m else "?"
            if m.group(1) == "PASS":
                return "PASS" if task == "bmc" else "PROVEN", f"{secs}s"
            fail_m = re.search(r"failed assertion ([\w.]+)", log)
            prop = fail_m.group(1) if fail_m else "unknown property"
            return "FAIL", f"{prop}, {secs}s"
        return "UNPARSED", "no DONE (PASS|FAIL) line found -- inspect raw log"

    if task == "cover":
        # Opposite polarity from bmc/pdr: DONE (PASS) here means the cover()
        # condition WAS reached -- a good result, confirming the property
        # this task exists to check is not vacuous. DONE (FAIL) means it was
        # NOT reached within depth, which is the informative, bad-news
        # outcome (mirrors how this project found sync_fifo_pipelined's
        # documented deadlock bug: the assert alone reported PROVEN in 0s
        # because its guard was unreachable, and only a cover check caught
        # that the guard was never satisfiable at all).
        m = re.search(r"DONE \((PASS|FAIL)", log)
        if m:
            time_m = re.search(r"Elapsed clock time.*\((\d+)\)", log)
            secs = time_m.group(1) if time_m else "?"
            if m.group(1) == "PASS":
                return "REACHED", f"{secs}s"
            return "UNREACHABLE", f"not reached within depth, {secs}s -- the guard condition may be vacuous"
        return "UNPARSED", "no DONE (PASS|FAIL) line found -- inspect raw log"

    if task == "prove":
        base_m = re.search(r"returned pass for basecase", log)
        base = "PASS" if base_m else ("FAIL" if "returned FAIL for basecase" in log else "UNKNOWN")
        ind_m = re.search(r"returned pass for induction", log)
        if ind_m:
            ind = "PASS"
        elif "returned FAIL for induction" in log:
            ind = "FAIL"
        else:
            ind = "UNKNOWN"
        fail_prop = ""
        if ind == "FAIL":
            fp = re.search(r"Assert failed in \w+: (\w+)", log)
            fail_prop = f" ({fp.group(1)})" if fp else ""
        if base == "PASS" and ind == "PASS":
            return "PROVEN", "k-induction closed"
        return "PARTIAL", f"basecase={base}, induction={ind}{fail_prop}"

    return "UNPARSED", "unknown task"


def main():
    ap = argparse.ArgumentParser(
        description="Generate the standard SBY config and run bmc/prove/pdr (see module docstring).",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--top", required=True, help="top-level miter module name")
    ap.add_argument("--file", action="append", required=True, dest="files",
                     help="source file, relative to --workdir; repeatable, order matters for read_verilog")
    ap.add_argument("--workdir", required=True, help="directory containing the source files (matches this project's experiments/<name>/ convention)")
    ap.add_argument("--depth", type=int, default=40, help="bmc/prove depth (default 40, matching every proof in this project so far)")
    ap.add_argument("--tasks", default="bmc,prove,pdr", help="comma-separated subset of bmc,prove,pdr,cover to run -- add cover whenever the miter has a cover() statement (every branch-3/stream-equivalence proof should)")
    ap.add_argument("--timeout", type=int, default=280, help="per-task wall-clock timeout in seconds (default 280 -- this project's multiplier-bearing proof needed ~175s for pdr)")
    ap.add_argument("--sby-bin", default="sby", help="path to the sby binary")
    ap.add_argument("--sby-name", default=None, help="basename for the generated .sby file (default: <top>.sby)")
    args = ap.parse_args()

    sby_name = args.sby_name or f"{args.top}.sby"
    sby_path = os.path.join(args.workdir, sby_name)
    sby_text = build_sby(args.top, args.files, args.depth)
    with open(sby_path, "w", encoding="utf-8") as f:
        f.write(sby_text)
    print(f"wrote {sby_path}")

    tasks = [t.strip() for t in args.tasks.split(",") if t.strip()]
    results = {}
    for task in tasks:
        print(f"\n--- running {task} (timeout {args.timeout}s) ---", flush=True)
        rc, log, timed_out = run_task(args.sby_bin, sby_path, task, args.workdir, args.timeout)
        verdict, detail = parse_result(task, log, timed_out)
        results[task] = (verdict, detail)
        print(f"{task}: {verdict} -- {detail}")
        log_path = os.path.join(args.workdir, f"{args.top}_{task}.raw.log")
        with open(log_path, "w", encoding="utf-8") as f:
            f.write(log)
        print(f"  raw log: {log_path}")

    print("\n=== summary ===")
    print(f"{'task':<8} {'verdict':<10} detail")
    for task in tasks:
        verdict, detail = results[task]
        print(f"{task:<8} {verdict:<10} {detail}")

    if "cover" in results and results["cover"][0] == "UNREACHABLE":
        overall = "cover UNREACHABLE -- any PROVEN/PASS above may be VACUOUS, do not trust it without investigating"
    elif any(v[0] in ("PASS", "PROVEN") for v in results.values()):
        overall = "at least one engine closed the property"
    else:
        overall = "no engine closed the property within budget -- not necessarily false, inspect raw logs"
    print(f"\noverall: {overall}")


if __name__ == "__main__":
    main()
